### ISSUE TITLE
Suscribe Steering Wheel Button

### ISSUE THREAD

**Issue by NDNELSON** [smartdevicelink/sdl_mobileweather_tutorial_android#3]
Hello Could anyone help me please? I have tried how to suscribe a physical button or steering wheel button Push-To-Talk. I would like to get the long press event of this button to start my own service

I have tried it in this way:
proxy.subscribeButton(ButtonName.valueForString("Push-To-Talk"), nextCorrelationID());
and:

proxy.subscribeButton(ButtonName.PTT), nextCorrelationID());

but it doesnt work or can not resolve symbol in android

**Comment by joeygrover** [comment]
Closed because of duplicate question, see smartdevicelink/sdl_android#287
